#!/bin/sh

scriptDir=$(dirname -- "$(readlink -f -- "$BASH_SOURCE")")
consoleDir="$scriptDir/bin/console"
webDir="$scriptDir/web"

cd $webDir && yarn install && yarn add node-sass && yarn run build && cd ..
php $consoleDir server:start 0.0.0.0 -p 8000 --force
php $consoleDir gos:web:ser --env=prod

exit 1