#!/bin/bash

kill $(ps aux | grep 'server:start' | awk '{print $2}') 2>/dev/null
kill $(ps aux | grep 'gos:web' | awk '{print $2}') 2>/dev/null
kill $(ps aux | grep 'chromium-browser' | grep 'http://127.0.0.1:8000'  | awk '{print $2}') 2>/dev/null

exit;