parameters:
  fish.neat.command.class: Gheb\Fish\NeatBundle\Command\NeatCommand
  fish.neat.mutation.class: Gheb\Fish\NeatBundle\Network\Mutation

services:

  fish.neat.mutation:
    class: "%fish.neat.mutation.class%"
    arguments: ["@doctrine.orm.entity_manager", "@fish.io.aggregator.inputs", "@fish.io.aggregator.outputs"]

  fish.neat.command:
    class: %fish.neat.command.class%
    arguments: ["@fish.io.aggregator.inputs", "@fish.io.aggregator.outputs", "@doctrine.orm.entity_manager", "@fish.neat.mutation"]
    tags:
      - { name: console.command }