parameters:
  fish.io.aggregator.inputs.class: Gheb\Fish\IOBundle\Inputs\InputsAggregator
  fish.io.aggregator.outputs.class: Gheb\Fish\IOBundle\Outputs\OutputsAggregator
  fish.io.command.outputs.class: Gheb\Fish\IOBundle\Command\OutputsCommand
  fish.io.command.inputs.class: Gheb\Fish\IOBundle\Command\InputsCommand

services:
  fish.logger.io:
    class: Gheb\Fish\IOBundle\Monolog\IOLogger
    arguments: ['@logger']
    tags:
        - { name: monolog.logger, channel: io }

  fish.io.aggregator.inputs:
    class: %fish.io.aggregator.inputs.class%
    arguments: ["@doctrine.orm.entity_manager", "@fish.logger.io"]
    calls:
      - [aggregate]

  fish.io.aggregator.outputs:
    class: %fish.io.aggregator.outputs.class%
    arguments: ["@doctrine.orm.entity_manager", "@fish.logger.io"]
    calls:
      - [aggregate]

  fish.io.command.ouputs:
    class: %fish.io.command.outputs.class%
    arguments: [ '@fish.io.aggregator.outputs' ]
    tags:
      - { name: console.command }

  fish.io.command.inputs:
    class: %fish.io.command.inputs.class%
    arguments: [ '@fish.io.aggregator.inputs' ]
    tags:
      - { name: console.command }