parameters:
  fish.command.apply.life.class: Gheb\Fish\FishBundle\Command\ApplyLifeCommand
  fish.command.apply.time.class: Gheb\Fish\FishBundle\Command\ApplyTimeCommand
  fish.command.givebirth.class: Gheb\Fish\FishBundle\Command\GiveBirthCommand
  fish.command.kill.class: Gheb\Fish\FishBundle\Command\KillCommand

  fish.life.class: Gheb\Fish\FishBundle\Services\Life
  fish.life.obligation.hunger.class: Gheb\Fish\FishBundle\Services\HungerObligation
  fish.life.obligation.playfull.class: Gheb\Fish\FishBundle\Services\PlayfullObligation
  fish.life.obligation.sleepiness.class: Gheb\Fish\FishBundle\Services\SleepinessObligation
  fish.life.obligation.time.class: Gheb\Fish\FishBundle\Services\TimeObligation

  fish.io.input.hunger.class : Gheb\Fish\FishBundle\IO\Inputs\Hunger
  fish.io.input.playfull.class : Gheb\Fish\FishBundle\IO\Inputs\Playfull
  fish.io.input.sleepiness.class : Gheb\Fish\FishBundle\IO\Inputs\Sleepiness

  fish.io.output.feed.class : Gheb\Fish\FishBundle\IO\Outputs\Feed
  fish.io.output.play.class : Gheb\Fish\FishBundle\IO\Outputs\Play
  fish.io.output.puttobed.class : Gheb\Fish\FishBundle\IO\Outputs\PutToBed
  fish.io.output.nothing.class : Gheb\Fish\FishBundle\IO\Outputs\Nothing

  fish.neat.hook.afterEvaluation.class: Gheb\Fish\FishBundle\Neat\AfterEvaluationHook
  fish.neat.hook.getfitness.class: Gheb\Fish\FishBundle\Neat\GetFitnessHook
  fish.neat.hook.beforeinit.class: Gheb\Fish\FishBundle\Neat\BeforeInitHook
  fish.neat.hook.beforenewrun.class: Gheb\Fish\FishBundle\Neat\BeforeNewRunHook
  fish.neat.hook.nextgenomecriteria.class: Gheb\Fish\FishBundle\Neat\NextGenomeCriteriaHook

services:

  fish.command.givebirth:
    class: %fish.command.givebirth.class%
    arguments: [ "@doctrine.orm.entity_manager" ]
    tags:
      - { name: console.command }

  fish.command.kill:
    class: %fish.command.kill.class%
    arguments: [ "@doctrine.orm.entity_manager" ]
    tags:
      - { name: console.command }

  fish.command.apply.life:
    class: %fish.command.apply.life.class%
    arguments: [ "@doctrine.orm.entity_manager", "@fish.life" ]
    tags:
      - { name: console.command }

  fish.command.apply.time:
    class: %fish.command.apply.time.class%
    arguments: [ "@doctrine.orm.entity_manager", "@fish.life.obligation.time" ]
    tags:
      - { name: console.command }

  fish.life:
    class: %fish.life.class%

  fish.life.obligation.hunger:
    class: %fish.life.obligation.hunger.class%
    public: false
    tags:
      - { name: fish.life.obligation }

  fish.life.obligation.playfull:
    class: %fish.life.obligation.playfull.class%
    public: false
    tags:
      - { name: fish.life.obligation }

  fish.life.obligation.sleepiness:
    class: %fish.life.obligation.sleepiness.class%
    public: false
    tags:
      - { name: fish.life.obligation }

  fish.life.obligation.time:
    class: %fish.life.obligation.time.class%
    public: false

  fish.io.input.hunger:
    class : '%fish.io.input.hunger.class%'
    arguments: [ "@doctrine.orm.entity_manager" ]
    tags:
      - { name: gheb.io.input }

  fish.io.input.playfull:
    class : '%fish.io.input.playfull.class%'
    arguments: [ "@doctrine.orm.entity_manager" ]
    tags:
      - { name: gheb.io.input }

  fish.io.input.sleepiness:
    class : '%fish.io.input.sleepiness.class%'
    arguments: [ "@doctrine.orm.entity_manager" ]
    tags:
      - { name: gheb.io.input }

  fish.io.output.feed:
    class : '%fish.io.output.feed.class%'
    arguments: [ "@doctrine.orm.entity_manager" ]
    tags:
      - { name: gheb.io.output }

  fish.io.output.nothing:
    class : '%fish.io.output.nothing.class%'
    arguments: [ "@doctrine.orm.entity_manager" ]
    tags:
      - { name: gheb.io.output }

  fish.io.output.play:
    class : '%fish.io.output.play.class%'
    arguments: [ "@doctrine.orm.entity_manager" ]
    tags:
      - { name: gheb.io.output }

  fish.io.output.puttobed:
    class : '%fish.io.output.puttobed.class%'
    arguments: [ "@doctrine.orm.entity_manager" ]
    tags:
      - { name: gheb.io.output }

  fish.neat.hook.afterevaluation:
    class: '%fish.neat.hook.afterEvaluation.class%'
    arguments: [ "@doctrine.orm.entity_manager", "@fish.life.obligation.time", "@fish.life" ]
    tags:
      - { name: gheb.neat.hook.onAfterEvaluation }

  fish.neat.hook.getfitness:
    class: '%fish.neat.hook.getfitness.class%'
    arguments: [ "@doctrine.orm.entity_manager" ]
    tags:
      - { name: gheb.neat.hook.getFitness }

  fish.neat.hook.beforeinit:
    class: '%fish.neat.hook.beforeinit.class%'
    arguments: [ "@doctrine.orm.entity_manager" ]
    tags:
      - { name: gheb.neat.hook.onBeforeInit }

  fish.neat.hook.beforenewrun:
    class: '%fish.neat.hook.beforenewrun.class%'
    arguments: [ "@doctrine.orm.entity_manager" ]
    tags:
      - { name: gheb.neat.hook.onBeforeNewRun }

  fish.neat.hook.nextgenomecriteria:
    class: '%fish.neat.hook.nextgenomecriteria.class%'
    arguments: [ "@doctrine.orm.entity_manager" ]
    tags:
      - { name: gheb.neat.hook.nextGenomeCriteria }
