Gheb\Fish\NeatBundle\Network\Gene:
  type: entity
  table: Gene
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    enabled:
      type: boolean
    innovation:
      type: integer
    into:
      column: fromNeuron
      type: integer
    out:
      column: toNeuron
      type: integer
    weight:
      type: decimal
      precision: 8
      scale: 2

  manyToOne:
    genome:
      targetEntity: 'Gheb\Fish\NeatBundle\Network\Genome'
      cascade: ['persist', 'remove', 'refresh']
      orphanRemoval: true
      inversedBy: genes
      joinColumn:
        name: genome_id
        referencedColumnName: id
        onDelete: CASCADE