Gheb\Fish\NeatBundle\Network\Genome:
  type: entity
  table: Genome
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    fitness:
      type: integer
    maxNeuron:
      type: integer
    mutationRates:
      type: array
    globalRank:
      type: integer

  oneToMany:
    genes:
      targetEntity: 'Gheb\Fish\NeatBundle\Network\Gene'
      cascade: ['persist', 'remove', 'refresh']
      mappedBy: genome

  manyToOne:
    specie:
      targetEntity: 'Gheb\Fish\NeatBundle\Network\Specie'
      cascade: ['persist', 'remove', 'refresh']
      inversedBy: genomes
      joinColumn:
        name: specie_id
        referencedColumnName: id

  manyToMany:
    network:
      targetEntity: 'Gheb\Fish\NeatBundle\Network\Neuron'
      cascade: ['persist', 'remove', 'refresh']
      joinTable:
        name: Genome_neurons
        joinColumns:
          genome_id:
            referencedColumnName: id
        inverseJoinColumns:
          neuron_id:
            referencedColumnName: id
            unique: true