Gheb\Fish\NeatBundle\Network\Pool:
  type: entity
  table: Pool
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    currentGenome:
      type: integer
    currentSpecies:
      type: integer
    generation:
      type: integer
    innovation:
      type: integer
    maxFitness:
      type: integer

  oneToMany:
    species:
      targetEntity: 'Gheb\Fish\NeatBundle\Network\Specie'
      cascade: ['persist', 'remove', 'refresh']
      mappedBy: pool