Gheb\Fish\NeatBundle\Network\Specie:
  type: entity
  table: Specie
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    averageFitness:
      type: integer
    staleness:
      type: integer
    topFitness:
      type: integer

  oneToMany:
    genomes:
      targetEntity: 'Gheb\Fish\NeatBundle\Network\Genome'
      cascade: ['persist', 'remove', 'refresh']
      orphanRemoval: true
      mappedBy: specie
  manyToOne:
    pool:
      targetEntity: 'Gheb\Fish\NeatBundle\Network\Pool'
      cascade: ['persist', 'remove', 'refresh']
      orphanRemoval: true
      inversedBy: species
      joinColumn:
        name: pool_id
        referencedColumnName: id