FishBundle\Entity\Fish:
    type: entity
    table: fish
    repositoryClass: FishBundle\Entity\FishRepository
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        lifeTick:
            type: integer
        health:
            type: integer
        hunger:
            type: integer
        sleepiness:
            type: integer
        playfull:
            type: integer
        weight:
            type: integer
        wealth:
            type: integer
